import talib
import numpy as np
from matplotlib.table import table


class TechnicalAnalysisComplete:
    def __init__(self, open, high, low, close, volume):
        self.open = open
        self.high = high
        self.low = low
        self.close = close
        self.volume = volume

    def execute(self):
        return np.array([self.open,
                         self.high,
                         self.low,
                         self.close,
                         self.volume,
                         talib.HT_DCPERIOD(self.close),
                         talib.HT_DCPHASE(self.close),
                         talib.HT_PHASOR(self.close)[0],
                         talib.HT_PHASOR(self.close)[1],
                         talib.HT_SINE(self.close)[0],
                         talib.HT_SINE(self.close)[1],
                         talib.HT_TRENDMODE(self.close),
                         talib.ADX(self.high, self.low, self.close),
                         talib.ADXR(self.high, self.low, self.close),
                         talib.APO(self.close),
                         talib.AROON(self.high, self.low)[0],
                         talib.AROON(self.high, self.low)[1],
                         talib.AROONOSC(self.high, self.low),
                         talib.BOP(self.open, self.high, self.low, self.close),
                         talib.CCI(self.high, self.low, self.close),
                         talib.CMO(self.close),
                         talib.DX(self.high, self.low, self.close),
                         talib.MACD(self.close)[0],
                         talib.MACD(self.close)[1],
                         talib.MACD(self.close)[2],
                         talib.MACDEXT(self.close)[0],
                         talib.MACDEXT(self.close)[1],
                         talib.MACDEXT(self.close)[2],
                         talib.MACDFIX(self.close)[0],
                         talib.MACDFIX(self.close)[1],
                         talib.MACDFIX(self.close)[2],
                         talib.MFI(self.high, self.low, self.close, self.volume),
                         talib.MINUS_DI(self.high, self.low, self.close),
                         talib.MINUS_DM(self.high, self.low),
                         talib.MOM(self.close),
                         talib.PLUS_DI(self.high, self.low, self.close),
                         talib.PLUS_DM(self.high, self.low),
                         talib.PPO(self.close),
                         talib.ROC(self.close),
                         talib.ROCP(self.close),
                         talib.ROCR(self.close),
                         talib.ROCR100(self.close),
                         talib.RSI(self.close),
                         talib.STOCH(self.high, self.low, self.close)[0],
                         talib.STOCH(self.high, self.low, self.close)[1],
                         talib.STOCHF(self.high, self.low, self.close)[0],
                         talib.STOCHF(self.high, self.low, self.close)[1],
                         talib.STOCHRSI(self.close)[0],
                         talib.STOCHRSI(self.close)[1],
                         talib.TRIX(self.close),
                         talib.ULTOSC(self.high, self.low, self.close),
                         talib.WILLR(self.high, self.low, self.close),
                         talib.BBANDS(self.close)[0],
                         talib.BBANDS(self.close)[1],
                         talib.BBANDS(self.close)[2],
                         talib.DEMA(self.close),
                         talib.EMA(self.close),
                         talib.HT_TRENDLINE(self.close),
                         talib.KAMA(self.close),
                         talib.MA(self.close),
                         talib.MAMA(self.close)[0],
                         talib.MAMA(self.close)[1],
                         talib.MIDPOINT(self.close),
                         talib.MIDPRICE(self.high, self.low),
                         talib.SAR(self.high, self.low),
                         talib.SAREXT(self.high, self.low),
                         talib.T3(self.close),
                         talib.TEMA(self.close),
                         talib.TRIMA(self.close),
                         talib.WMA(self.close),
                         talib.AVGPRICE(self.open, self.high, self.low, self.close),
                         talib.MEDPRICE(self.high, self.low),
                         talib.TYPPRICE(self.high, self.low, self.close),
                         talib.WCLPRICE(self.high, self.low, self.close),
                         talib.ATR(self.high, self.low, self.close),
                         talib.NATR(self.high, self.low, self.close),
                         talib.TRANGE(self.high, self.low, self.close),
                         talib.AD(self.high, self.low, self.close, self.volume),
                         talib.ADOSC(self.high, self.low, self.close, self.volume),
                         talib.OBV(self.close, self.volume),
                         talib.CDL2CROWS(self.open, self.high, self.low, self.close),
                         talib.CDL3BLACKCROWS(self.open, self.high, self.low, self.close),
                         talib.CDL3INSIDE(self.open, self.high, self.low, self.close),
                         talib.CDL3LINESTRIKE(self.open, self.high, self.low, self.close),
                         talib.CDL3OUTSIDE(self.open, self.high, self.low, self.close),
                         talib.CDL3STARSINSOUTH(self.open, self.high, self.low, self.close),
                         talib.CDL3WHITESOLDIERS(self.open, self.high, self.low, self.close),
                         talib.CDLABANDONEDBABY(self.open, self.high, self.low, self.close),
                         talib.CDLADVANCEBLOCK(self.open, self.high, self.low, self.close),
                         talib.CDLBELTHOLD(self.open, self.high, self.low, self.close),
                         talib.CDLBREAKAWAY(self.open, self.high, self.low, self.close),
                         talib.CDLCLOSINGMARUBOZU(self.open, self.high, self.low, self.close),
                         talib.CDLCONCEALBABYSWALL(self.open, self.high, self.low, self.close),
                         talib.CDLCOUNTERATTACK(self.open, self.high, self.low, self.close),
                         talib.CDLDARKCLOUDCOVER(self.open, self.high, self.low, self.close),
                         talib.CDLDOJI(self.open, self.high, self.low, self.close),
                         talib.CDLDOJISTAR(self.open, self.high, self.low, self.close),
                         talib.CDLDRAGONFLYDOJI(self.open, self.high, self.low, self.close),
                         talib.CDLENGULFING(self.open, self.high, self.low, self.close),
                         talib.CDLEVENINGDOJISTAR(self.open, self.high, self.low, self.close),
                         talib.CDLEVENINGSTAR(self.open, self.high, self.low, self.close),
                         talib.CDLGAPSIDESIDEWHITE(self.open, self.high, self.low, self.close),
                         talib.CDLGRAVESTONEDOJI(self.open, self.high, self.low, self.close),
                         talib.CDLHAMMER(self.open, self.high, self.low, self.close),
                         talib.CDLHANGINGMAN(self.open, self.high, self.low, self.close),
                         talib.CDLHARAMI(self.open, self.high, self.low, self.close),
                         talib.CDLHARAMICROSS(self.open, self.high, self.low, self.close),
                         talib.CDLHIGHWAVE(self.open, self.high, self.low, self.close),
                         talib.CDLHIKKAKE(self.open, self.high, self.low, self.close),
                         talib.CDLHIKKAKEMOD(self.open, self.high, self.low, self.close),
                         talib.CDLHOMINGPIGEON(self.open, self.high, self.low, self.close),
                         talib.CDLIDENTICAL3CROWS(self.open, self.high, self.low, self.close),
                         talib.CDLINNECK(self.open, self.high, self.low, self.close),
                         talib.CDLINVERTEDHAMMER(self.open, self.high, self.low, self.close),
                         talib.CDLKICKING(self.open, self.high, self.low, self.close),
                         talib.CDLKICKINGBYLENGTH(self.open, self.high, self.low, self.close),
                         talib.CDLLADDERBOTTOM(self.open, self.high, self.low, self.close),
                         talib.CDLLONGLEGGEDDOJI(self.open, self.high, self.low, self.close),
                         talib.CDLLONGLINE(self.open, self.high, self.low, self.close),
                         talib.CDLMARUBOZU(self.open, self.high, self.low, self.close),
                         talib.CDLMATCHINGLOW(self.open, self.high, self.low, self.close),
                         talib.CDLMATHOLD(self.open, self.high, self.low, self.close),
                         talib.CDLMORNINGDOJISTAR(self.open, self.high, self.low, self.close),
                         talib.CDLMORNINGSTAR(self.open, self.high, self.low, self.close),
                         talib.CDLONNECK(self.open, self.high, self.low, self.close),
                         talib.CDLPIERCING(self.open, self.high, self.low, self.close),
                         talib.CDLRICKSHAWMAN(self.open, self.high, self.low, self.close),
                         talib.CDLRISEFALL3METHODS(self.open, self.high, self.low, self.close),
                         talib.CDLSEPARATINGLINES(self.open, self.high, self.low, self.close),
                         talib.CDLSHOOTINGSTAR(self.open, self.high, self.low, self.close),
                         talib.CDLSHORTLINE(self.open, self.high, self.low, self.close),
                         talib.CDLSPINNINGTOP(self.open, self.high, self.low, self.close),
                         talib.CDLSTALLEDPATTERN(self.open, self.high, self.low, self.close),
                         talib.CDLSTICKSANDWICH(self.open, self.high, self.low, self.close),
                         talib.CDLTAKURI(self.open, self.high, self.low, self.close),
                         talib.CDLTASUKIGAP(self.open, self.high, self.low, self.close),
                         talib.CDLTHRUSTING(self.open, self.high, self.low, self.close),
                         talib.CDLTRISTAR(self.open, self.high, self.low, self.close),
                         talib.CDLUNIQUE3RIVER(self.open, self.high, self.low, self.close),
                         talib.CDLUPSIDEGAP2CROWS(self.open, self.high, self.low, self.close),
                         talib.CDLXSIDEGAP3METHODS(self.open, self.high, self.low, self.close),
                         ]).transpose()

